require("dotenv").config();
const express = require("express");
const cors = require("cors");
const { GoogleGenerativeAI } = require("@google/generative-ai");
const PptxGenJS = require("pptxgenjs");

const app = express();
app.use(cors());
app.use(express.json());

// ================= HEALTH =================
app.get("/", (req, res) => {
  res.send("🚀 SlideForge AI Ultra Backend Running");
});

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// ================= JSON SAFE =================
const extractJSON = (text) => {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  return JSON.parse(text.substring(start, end + 1));
};

// ================= IMAGE FETCH =================
const fetchImageBase64 = async (prompt) => {
  try {
    const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(
      prompt
    )}?width=1024&height=1024&nologo=true`;

    const response = await fetch(url);
    if (!response.ok) return null;

    const buffer = Buffer.from(await response.arrayBuffer());
    return `data:image/jpeg;base64,${buffer.toString("base64")}`;
  } catch {
    return null;
  }
};

// ================= AI GENERATION =================
app.post("/generate-json", async (req, res) => {
  try {
    const { topic } = req.body;

    const model = genAI.getGenerativeModel({
      model: "gemini-2.5-flash",
    });

    const prompt = `
Create a premium executive presentation about "${topic}".

Return ONLY JSON.

{
 "title":"Presentation Title",
 "slides":[
  {
   "type":"intro | content | image | summary",
   "heading":"Short heading",
   "points":["Point 1","Point 2","Point 3"],
   "speakerNotes":"Professional explanation",
   "imagePrompt":"Cinematic professional image"
  }
 ]
}

Rules:
- First slide intro
- Last slide summary
`;

    const result = await model.generateContent(prompt);
    const text = await result.response.text();

    res.json(extractJSON(text));
  } catch {
    res.status(500).json({ error: "Generation failed" });
  }
});

// ================= PPT ENGINE =================
app.post("/download-ppt", async (req, res) => {
  try {
    const { data } = req.body;

    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_16x9";

    const slides = await Promise.all(
      data.slides.map(async (s) => ({
        ...s,
        base64Image: await fetchImageBase64(s.imagePrompt),
      }))
    );

    // ========= COVER =========
    const cover = pptx.addSlide();
    cover.background = { fill: "020617" };

    cover.addText(data.title, {
      x: 1,
      y: 2,
      w: 8,
      h: 1.5,
      fontSize: 46,
      bold: true,
      color: "FFFFFF",
      align: "center",
    });

    cover.addText("Generated by SlideForge AI", {
      x: 1,
      y: 3.5,
      w: 8,
      h: 0.5,
      fontSize: 16,
      color: "94A3B8",
      align: "center",
    });

    // ========= DYNAMIC SLIDES =========
    slides.forEach((slide, index) => {
      const s = pptx.addSlide();
      const layout = slide.type || "content";

      if (slide.speakerNotes) s.addNotes(slide.speakerNotes);

      // ===== INTRO =====
      if (layout === "intro") {
        s.background = { fill: "020617" };

        s.addText(slide.heading, {
          x: 1,
          y: 2,
          w: 8,
          h: 1,
          fontSize: 42,
          bold: true,
          color: "FFFFFF",
          align: "center",
        });
      }

      // ===== CONTENT =====
      else if (layout === "content") {
        s.background = { fill: "0F172A" };

        s.addText(slide.heading, {
          x: 0.8,
          y: 0.8,
          w: 8,
          h: 1,
          fontSize: 34,
          bold: true,
          color: "FFFFFF",
        });

        s.addText(slide.points.join("\n"), {
          x: 1,
          y: 2.2,
          w: 4.5,
          h: 3,
          fontSize: 20,
          color: "CBD5F5",
          bullet: true,
          lineSpacing: 34,
        });

        if (slide.base64Image) {
          s.addImage({
            data: slide.base64Image,
            x: 5.6,
            y: 1.5,
            w: 3.6,
            h: 3,
          });
        }
      }

      // ===== IMAGE SLIDE =====
      else if (layout === "image") {
        s.background = { fill: "000000" };

        if (slide.base64Image) {
          s.addImage({
            data: slide.base64Image,
            x: 0,
            y: 0,
            w: 10,
            h: 5.6,
          });
        }

        s.addText(slide.heading, {
          x: 0.5,
          y: 4.2,
          w: 9,
          h: 1,
          fontSize: 28,
          bold: true,
          color: "FFFFFF",
          align: "center",
        });
      }

      // ===== SUMMARY =====
      else {
        s.background = { fill: "F8FAFC" };

        s.addText("Key Takeaways", {
          x: 1,
          y: 0.8,
          w: 8,
          h: 1,
          fontSize: 38,
          bold: true,
          align: "center",
        });

        s.addText(slide.points.join("\n"), {
          x: 2,
          y: 2,
          w: 6,
          h: 3,
          fontSize: 22,
          align: "center",
          bullet: true,
          lineSpacing: 36,
        });
      }

      // slide number
      s.addText(`${index + 1}`, {
        x: 9,
        y: 5.1,
        w: 0.5,
        h: 0.3,
        fontSize: 12,
        color: "94A3B8",
      });
    });

    const buffer = await pptx.write("nodebuffer");

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    );

    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${data.title.replace(/[^a-z0-9]/gi, "_")}.pptx"`
    );

    res.send(buffer);
  } catch (err) {
    console.log(err);
    res.status(500).json({ error: "PPT generation failed" });
  }
});

// ================= PORT =================
const PORT = process.env.PORT || 5000;
app.listen(PORT, () =>
  console.log(`🔥 SlideForge Ultra running on ${PORT}`)
);